---
services:
  db:
    image: postgres:latest
    ports:
      - "8532:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-template_db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-template_db_password}
      POSTGRES_DB: ${DB_NAME:-template_db_dev}