# nixpacks.toml
# Configuration for deploying your Clojure application on Railway with Nixpacks.

providers = []

[phases.setup]
nixFile = "./environment.nix"

[phases.build]
cmds = [
  "echo 'Downloading Clojure dependencies...'",
  "nix-shell environment.nix --run \"clojure -P\"", # Run clojure -P within the Nix shell
  "echo 'Clojure dependencies ready.'",
  "echo 'Cleaning up Clojure/Maven caches...'",
  "rm -rf /root/.m2 /root/.clojure /app/.cpcache", # Attempt to remove common cache locations
  "echo 'Caches cleaned.'",
  "echo 'Installing npm dependencies...'",
  "npm install --prefer-offline --no-audit --progress=false",
  "echo 'npm dependencies ready.'"
]

[start]
cmd = "clojure -M -m zi-study.repl $PORT"

[env]
JVM_ENV = "production"
NODE_ENV = "production"