(ns backend.e2e.support
  (:require [backend.routes :as routes]
            [cheshire.core :as json]
            [cognitect.transit :as transit]
            [clojure.string :as str]
            [next.jdbc :as jdbc]
            [ring.mock.request :as mock])
  (:import (java.io ByteArrayOutputStream File)))

(defn h2-datasource []
  (jdbc/get-datasource
   {:jdbcUrl "jdbc:h2:mem:zistudy_e2e;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"}))

(defn setup-schema! [ds]
  ;; Minimal schema compatible with the app
  (doseq [sql ["CREATE TABLE IF NOT EXISTS app_user (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  email VARCHAR UNIQUE NOT NULL,
                  password_hash VARCHAR,
                  name VARCHAR,
                  provider VARCHAR,
                  provider_id VARCHAR,
                  avatar_url VARCHAR,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );"
               "CREATE TABLE IF NOT EXISTS todo (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  text VARCHAR,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                  status VARCHAR DEFAULT 'unresolved'
                );"]]
    (jdbc/execute! ds [sql])))

(defn- tmp-dir []
  (let [d (File/createTempFile "e2e-uploads-" "-dir")] (.delete d) (.mkdirs d) (.getAbsolutePath d)))

(defn handler [ds]
  (routes/app {:db ds
               :env {:session {:secret "0123456789ABCDEF"}
                     :uploads {:root (tmp-dir)}}}))

(defn transit-json [data]
  (let [out (ByteArrayOutputStream.)
        w (transit/writer out :json)]
    (transit/write w data)
    (.toString out "UTF-8")))

(defn json-body [m]
  (json/generate-string m))

(defn with-csrf [req]
  (mock/header req "x-csrf-token" "test"))

(defn cookie-from [resp]
  (let [h (get-in resp [:headers "Set-Cookie"])
        hs (cond
             (string? h) [h]
             (sequential? h) h
             :else [])]
    (some (fn [s]
            (let [first-part (first (str/split s #";"))]
              (when (str/starts-with? first-part "sid=")
                first-part)))
          hs)))

(defn request-with-cookie [method path cookie]
  (cond-> (mock/request method path)
    cookie (mock/header "Cookie" cookie)))
